# this is the build file for project Sandbox
# it is autogenerated by the xmake build system.
# do not edit by hand.

!if "$(VERBOSE)" != "1"
VV=@
!endif

MRC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\rc.exe
AS=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64\ml64.exe
CC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64\cl.exe
CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64\cl.exe

LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64\link.exe
AR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64\link.exe
SH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64\link.exe

ArXFX_LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64\link.exe
ArXFX_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64\cl.exe
ArXFX_CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX64\x64\cl.exe

ArXFX_CXXFLAGS=-nologo -Zi -FS -Fdbuild\windows\x64\Release\compile.ArXFX.pdb -std:c++20 -MTd -IArX\include -Isrc -DAFX_ARCH_X64 -DAFX_RELEASE /EHsc
ArXFX_CXXFLAGS=-nologo -Zi -FS -Fdbuild\windows\x64\Release\compile.ArXFX.pdb -std:c++20 -MTd -IArX\include -Isrc -DAFX_ARCH_X64 -DAFX_RELEASE /EHsc
ArXFX_LDFLAGS=-nologo -dynamicbase -nxcompat -machine:x64 /opt:ref /opt:icf -debug -pdb:build\windows\x64\Release\ArXFX.pdb -nodefaultlib:msvcrt.lib

default:  ArXFX

all:  ArXFX

.PHONY: default all  ArXFX

ArXFX: build\windows\x64\Release\ArXFX.exe
build\windows\x64\Release\ArXFX.exe: build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\LowLevelGraphics.cpp.obj build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs\CitraGraphics.cpp.obj build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs\OpenGLGraphics.cpp.obj build\.objs\ArXFX\windows\x64\Release\src\arg\gfx\impl_opengl\gfx.cpp.obj build\.objs\ArXFX\windows\x64\Release\src\arg\imgui\vk_imgui.cpp.obj build\.objs\ArXFX\windows\x64\Release\src\main.cpp.obj
	@echo linking.Release ArXFX.exe
	-@mkdir build\windows\x64\Release > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x64\\link.exe" $(ArXFX_LDFLAGS) -out:build\windows\x64\Release\ArXFX.exe build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\LowLevelGraphics.cpp.obj build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs\CitraGraphics.cpp.obj build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs\OpenGLGraphics.cpp.obj build\.objs\ArXFX\windows\x64\Release\src\arg\gfx\impl_opengl\gfx.cpp.obj build\.objs\ArXFX\windows\x64\Release\src\arg\imgui\vk_imgui.cpp.obj build\.objs\ArXFX\windows\x64\Release\src\main.cpp.obj

build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\LowLevelGraphics.cpp.obj: src\afx\Renderer\LowLevel\LowLevelGraphics.cpp
	@echo compiling.Release src\afx\Renderer\LowLevel\LowLevelGraphics.cpp
	-@mkdir build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x64\\cl.exe" -c $(ArXFX_CXXFLAGS) -Fobuild\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\LowLevelGraphics.cpp.obj src\afx\Renderer\LowLevel\LowLevelGraphics.cpp

build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs\CitraGraphics.cpp.obj: src\afx\Renderer\LowLevel\Stubs\CitraGraphics.cpp
	@echo compiling.Release src\afx\Renderer\LowLevel\Stubs\CitraGraphics.cpp
	-@mkdir build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x64\\cl.exe" -c $(ArXFX_CXXFLAGS) -Fobuild\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs\CitraGraphics.cpp.obj src\afx\Renderer\LowLevel\Stubs\CitraGraphics.cpp

build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs\OpenGLGraphics.cpp.obj: src\afx\Renderer\LowLevel\Stubs\OpenGLGraphics.cpp
	@echo compiling.Release src\afx\Renderer\LowLevel\Stubs\OpenGLGraphics.cpp
	-@mkdir build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x64\\cl.exe" -c $(ArXFX_CXXFLAGS) -Fobuild\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs\OpenGLGraphics.cpp.obj src\afx\Renderer\LowLevel\Stubs\OpenGLGraphics.cpp

build\.objs\ArXFX\windows\x64\Release\src\arg\gfx\impl_opengl\gfx.cpp.obj: src\arg\gfx\impl_opengl\gfx.cpp
	@echo compiling.Release src\arg\gfx\impl_opengl\gfx.cpp
	-@mkdir build\.objs\ArXFX\windows\x64\Release\src\arg\gfx\impl_opengl > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x64\\cl.exe" -c $(ArXFX_CXXFLAGS) -Fobuild\.objs\ArXFX\windows\x64\Release\src\arg\gfx\impl_opengl\gfx.cpp.obj src\arg\gfx\impl_opengl\gfx.cpp

build\.objs\ArXFX\windows\x64\Release\src\arg\imgui\vk_imgui.cpp.obj: src\arg\imgui\vk_imgui.cpp
	@echo compiling.Release src\arg\imgui\vk_imgui.cpp
	-@mkdir build\.objs\ArXFX\windows\x64\Release\src\arg\imgui > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x64\\cl.exe" -c $(ArXFX_CXXFLAGS) -Fobuild\.objs\ArXFX\windows\x64\Release\src\arg\imgui\vk_imgui.cpp.obj src\arg\imgui\vk_imgui.cpp

build\.objs\ArXFX\windows\x64\Release\src\main.cpp.obj: src\main.cpp
	@echo compiling.Release src\main.cpp
	-@mkdir build\.objs\ArXFX\windows\x64\Release\src > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x64\\cl.exe" -c $(ArXFX_CXXFLAGS) -Fobuild\.objs\ArXFX\windows\x64\Release\src\main.cpp.obj src\main.cpp

clean:  clean_ArXFX

clean_ArXFX: 
	@del /F /Q build\windows\x64\Release\ArXFX.exe > NUL 2>&1 || rmdir /S /Q build\windows\x64\Release\ArXFX.exe > NUL 2>&1
	@del /F /Q build\windows\x64\Release\ArXFX.pdb > NUL 2>&1 || rmdir /S /Q build\windows\x64\Release\ArXFX.pdb > NUL 2>&1
	@del /F /Q build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\LowLevelGraphics.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\LowLevelGraphics.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs\CitraGraphics.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs\CitraGraphics.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs\OpenGLGraphics.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\ArXFX\windows\x64\Release\src\afx\Renderer\LowLevel\Stubs\OpenGLGraphics.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\ArXFX\windows\x64\Release\src\arg\gfx\impl_opengl\gfx.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\ArXFX\windows\x64\Release\src\arg\gfx\impl_opengl\gfx.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\ArXFX\windows\x64\Release\src\arg\imgui\vk_imgui.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\ArXFX\windows\x64\Release\src\arg\imgui\vk_imgui.cpp.obj > NUL 2>&1
	@del /F /Q build\.objs\ArXFX\windows\x64\Release\src\main.cpp.obj > NUL 2>&1 || rmdir /S /Q build\.objs\ArXFX\windows\x64\Release\src\main.cpp.obj > NUL 2>&1

